stages:
  windower:
    cmd: python sliding_windows.py
    deps:
      - sliding_windows.py
      - config.py
      - data/accelerometer.csv
    params:
      - windower.windows_size
      - windower.step
    outs:
      - data/windows.npy
  reducer:
    cmd: python dimension_reduction.py
    deps:
      - dimension_reduction.py
      - config.py
      - data/windows.npy
    params:
      - reducer.random_state
    outs:
      - plots/tsne.png
plots:
  - plots/tsne.png